### ISSUE TITLE
Create Blog Card

### ISSUE THREAD

**Issue by AhmadHRai** [202212-GIZ-YE-FEW/Tabadul#7]
**Task title**
Create Blog Card

**Task description**
Create a Single Blog Card that contains the following:
1. Image
2. Date in the format of DD MMM
3. Blog title
4. Blog description (a paragraph no more than 4 lines)

**Screenshots**
![image](https://user-images.githubusercontent.com/72130324/227800136-981bbd22-fa37-482d-83bd-8ddb5081e212.png)

**Link to the component on Figma**
[Link here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?node-id=93-44&t=gtVRBgfl0DtNeWIx-0)
![image](https://user-images.githubusercontent.com/72130324/227800198-1bb4d23a-c558-482c-a5c5-4e9433a7e602.png)

**Comment by sra1kumar-NULL** [comment]
hey @AhmadHRai  could you assign me this issue . I would love to work on this

**Comment by AhmadHRai** [comment]
@sra1kumar-NULL I would love to but unfortunately it is *my* capstone and *I* have to work on it myself. Lets work together on other projects instead!

**Comment by sra1kumar-NULL** [comment]
> @sra1kumar-NULL I would love to but unfortunately it is _my_ capstone and _I_ have to work on it myself. Lets work together on other projects instead!

Yeah Great let's catch up later then @AhmadHRai  thanks for the quick response though
